repos:
- repo: https://github.com/asottile/pyupgrade
  rev: v2.31.1
  hooks:
  - id: pyupgrade
    args: ["--py36-plus"]
- repo: https://github.com/psf/black
  rev: 22.1.0
  hooks:
  - id: black
- repo: https://github.com/pycqa/flake8
  rev: 4.0.1
  hooks:
  - id: flake8
    args: ["--max-line-length=88", "--extend-ignore=E203,E501,E712,F401"]
- repo: https://github.com/pycqa/isort
  rev: 5.10.1
  hooks:
  - id: isort
    args: ["--profile", "black"]
