name: Lint and Format Python Files

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install black flake8

      - name: Format Python files with black
        run: |
          black --check .

      - name: Lint Python files with flake8
        run: |
          flake8 --ignore=E501 .
