name: Publish deduplify to PyPI

on:
  release:
    - published

jobs:
  publish-pypi:
    runs-on: ubuntu-latest
    environment: pypi
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Python 3.9
        uses: actions/setup-python@v2.3.2
        with:
          python-version: 3.9

      - name: Install twine and wheel
        run: |
          python -m pip install -U pip
          python -m pip install twine wheel

      - name: Build distribution
        run: |
          python setup.py sdist bdist_wheel

      - name: Test distribution
        run: |
          twine check dist/*

      - name: Publish to PyPI
        run: |
          twine upload \
          -u __token__ \
          -p ${{ secrets.PYPI_PASSWORD }} \
          dist/*
